typography_spectrum: 0.783385026967153
color:
  brandStrength: 0.376381604000926
  saturation: 0.02078394265845418
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  lightness: 0.22595556010492146
  rhythmicContrast: 0.7701168833300471
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7188520734198391
analytics:
  twitter: null
  google: null
  facebook: null
name: Kiwi Enterprises
cta:
  version: null
  bucket: null
  domain: null
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Kiwi Enterprises
description: Quality. Change. Contribution.
purpose: []
