name: Kiwi Enterprises
favicon: null
layout_spectrum: 0.77148
typography_spectrum: 0.34221
title: Kiwi Enterprises
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5379101547878236
purpose: []
