name: Kiwi Enterprises
favicon: null
layout_spectrum: 0.6016212056856602
typography_spectrum: 0.14861093531362712
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5199222173541784
  lightness: 0.06721591856330633
  saturation: 0.028879657154902816
  rhythmicContrast: 0.5379101547878236
purpose: []
